ROSTemplateFormatVersion: '2015-09-01'
Description: Creates a simple oss bucket
Parameters:
  AccessControl:
    Default: public-read-write
    Label:
      zh-cn: 读写权限
      en: Access Control
    Type: String
    Description:
      zh-cn: 设置Bucket读写权限
      en: Set the access permission of the bucket
    AllowedValues:
      - private
      - public-read
      - public-read-write
  BucketName:
    Description:
      zh-cn: Bucket 名称
      en: Bucket name
    Default: laizhong-test-maz
    Type: String
    Label:
      zh-cn: 存储空间名称
      en: Bucket Name
    AllowedPattern: ^[a-z0-9]{1}[a-z0-9\-]{1,62}[a-z0-9]{1}$
    ConstraintDescription:
      zh-cn: 必须以小写字母或数字开头和结尾。长度在 [3, 63] 之内
      en: Must begin and be end with a lowercase letter or number. The length is within [3, 63]
Outputs:
  BucketDomainName:
    Value:
      Fn::GetAtt:
        - laizhong-test-maz
        - DomainName
Resources:
  laizhong-test-maz:
    Type: ALIYUN::OSS::Bucket
    Properties:
      AccessControl:
        Ref: AccessControl
      BucketName:
        Ref: BucketName
      Tags:
Metadata:
  ALIYUN::ROS::Interface:
    ParameterGroups:
      - Parameters:
          - BucketName
          - AccessControl
        Label:
          default: OSS
    TemplateTags:
      - acs:example:存储:创建一个OSSBucket
